export const data = {
    "display": "",
    "components": [
      {
        "label": "Enrollment Details",
        "tag": "p",
        "className": "",
        "attrs": [
          {
            "attr": "",
            "value": ""
          }
        ],
        "content": "<span style=\"color:#B87108\">ENROLLMENT DETAILS</span>\n<hr>",
        "refreshOnChange": false,
        "customClass": "",
        "hidden": false,
        "tableView": false,
        "modalEdit": false,
        "key": "enrollment_details",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "htmlelement",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "id": "em4ti5l"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Unique ID",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": true,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "unique_id",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "epu4fht",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Date of Reg/Transfer In",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": true,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "date_registration",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "prefix": "",
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "refreshOn": "",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "etx22z",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Date of Confirmed HIV Test",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "date_confirmed_hiv",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "prefix": "",
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "refreshOn": "",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "e47l7zvh",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "exi9md",
        "path": "columns"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "ART Status",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "resource": "",
                  "json": "",
                  "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=ART%20STATUS",
                  "custom": "",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "values": []
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.display }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "art_status",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "ebaeabka",
                "defaultValue": "",
                "selectValues": "",
                "disableLimit": false,
                "sort": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Care Entry Point",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "values": [
                    {}
                  ],
                  "resource": "",
                  "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=POINT_ENTRY",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "json": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.display }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "entry_point",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "disableLimit": false,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "e6w6cz",
                "defaultValue": {},
                "selectValues": "",
                "sort": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Facility Name",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "Enter facility name if care entry point is \"Transfer In'.",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "facility_name",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "e8bzzd9",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns1",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "eop7s1a",
        "path": "columns1"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Enrollment Setting",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "values": [
                    {}
                  ],
                  "resource": "",
                  "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=ENROLLMENT_SETTING",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "json": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.display }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "enrollment_setting",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "disableLimit": false,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "e3313ub",
                "defaultValue": {},
                "selectValues": "",
                "sort": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Source of Referral",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "values": [
                    {}
                  ],
                  "resource": "",
                  "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=SOURCE_REFERRAL",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "json": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.display }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "source_referral",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "disableLimit": false,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "egf4qrs",
                "defaultValue": {},
                "selectValues": "",
                "sort": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "HIV Status at Registration",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "values": [
                    {}
                  ],
                  "resource": "",
                  "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=HIV_STATUS",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "json": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.display }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "status_registration",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "disableLimit": false,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "eve9s9",
                "defaultValue": {},
                "selectValues": "",
                "sort": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns4",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "ee14nb8",
        "path": "columns4"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "TB Status",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "values": [
                    {}
                  ],
                  "resource": "",
                  "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=TB_STATUS",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "json": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.display }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "tb_status",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "disableLimit": false,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "el2rxig",
                "defaultValue": {},
                "selectValues": "",
                "sort": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Pregnancy",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "values": [
                    {}
                  ],
                  "resource": "",
                  "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=PREGANACY_STATUS",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "json": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.display }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "pregnancy_status",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "disableLimit": false,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "em4gm0n",
                "defaultValue": {},
                "selectValues": "",
                "sort": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns3",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "edawifn",
        "path": "columns3"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Enrolled into OVC?",
                "description": "<span style=\"color:blue\">*Tick if client is enrolled into ovc*",
                "tooltip": "",
                "shortcut": "",
                "inputType": "checkbox",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "defaultValue": false,
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "errorLabel": "",
                "key": "ovc_enrolled",
                "tags": [],
                "properties": {
                  "ovc_enrolled": "true"
                },
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [
                  {
                    "name": "onclick",
                    "trigger": {
                      "type": "javascript",
                      "javascript": "document.getElementById('ovc_enrolled').onchange = function() {\n    document.getElementById('ovc_number').disabled = !this.checked;\n};"
                    },
                    "actions": []
                  }
                ],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "checkbox",
                "input": true,
                "hideOnChildrenHidden": false,
                "placeholder": "",
                "prefix": "",
                "suffix": "",
                "multiple": false,
                "unique": false,
                "refreshOn": "",
                "labelPosition": "right",
                "widget": null,
                "validateOn": "change",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "dataGridLabel": true,
                "value": "",
                "name": "",
                "id": "e6g772d"
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "OVC Number",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "ovc_number",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": true,
                  "when": "ovc_enrolled",
                  "eq": "true",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "hideOnChildrenHidden": false,
                "refreshOn": "",
                "inputType": "text",
                "id": "ecjmizp",
                "defaultValue": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns2",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "ehfo1g2a",
        "path": "columns2"
      },
      {
        "label": "Submit",
        "action": "url",
        "showValidations": false,
        "theme": "primary",
        "size": "md",
        "block": false,
        "leftIcon": "fa fa-save",
        "rightIcon": "",
        "shortcut": "",
        "description": "",
        "tooltip": "",
        "customClass": "",
        "tabindex": "",
        "disableOnInvalid": true,
        "hidden": false,
        "autofocus": false,
        "disabled": false,
        "tableView": false,
        "modalEdit": false,
        "key": "submit",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "button",
        "input": true,
        "validate": {
          "unique": false,
          "multiple": false,
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "errorLabel": "",
        "hideLabel": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": {
          "type": "input"
        },
        "validateOn": "change",
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "dataGridLabel": true,
        "id": "ebdp9gc",
        "url": "https://lp-base-app.herokuapp.com/api/encounters",
        "headers": [
          {
            "header": "",
            "value": ""
          }
        ]
      }
    ]
  }