export const data = {
    "display": "",
    "components": [
      {
        "label": "HTML",
        "tag": "p",
        "className": "",
        "attrs": [
          {
            "attr": "",
            "value": ""
          }
        ],
        "content": "<span style=\"color:#B87108\">Indexing and Contact Tracing</span>\n<hr>",
        "refreshOnChange": false,
        "customClass": "",
        "hidden": false,
        "tableView": false,
        "modalEdit": false,
        "key": "html",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "htmlelement",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "id": "eqt8ss7"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Type of Contact",
                "widget": "choicesjs",
                "tableView": true,
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "json": "",
                  "url": "",
                  "resource": "",
                  "custom": ""
                },
                "selectThreshold": 0.3,
                "validate": {
                  "unique": false,
                  "multiple": false,
                  "required": false,
                  "custom": "",
                  "customPrivate": false,
                  "strictDateValidation": false
                },
                "key": "type_contact",
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "input": true,
                "hideOnChildrenHidden": false,
                "placeholder": "",
                "prefix": "",
                "customClass": "",
                "suffix": "",
                "multiple": false,
                "defaultValue": null,
                "protected": false,
                "unique": false,
                "persistent": true,
                "hidden": false,
                "clearOnHide": true,
                "refreshOn": "",
                "redrawOn": "",
                "modalEdit": false,
                "labelPosition": "top",
                "description": "",
                "errorLabel": "",
                "tooltip": "",
                "hideLabel": false,
                "tabindex": "",
                "disabled": false,
                "autofocus": false,
                "dbIndex": false,
                "customDefaultValue": "",
                "calculateValue": "",
                "attributes": {},
                "validateOn": "change",
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": ""
                },
                "overlay": {
                  "style": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "allowCalculateOverride": false,
                "encrypted": false,
                "showCharCount": false,
                "showWordCount": false,
                "properties": {},
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "limit": 100,
                "dataSrc": "values",
                "valueProperty": "",
                "lazyLoad": true,
                "filter": "",
                "searchEnabled": true,
                "searchField": "",
                "minSearch": 0,
                "readOnlyValue": false,
                "authenticate": false,
                "template": "<span>{{ item.label }}</span>",
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "customOptions": {},
                "id": "ef2uluj"
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Surname",
                "spellcheck": true,
                "tableView": true,
                "validate": {
                  "unique": false,
                  "multiple": false,
                  "required": false,
                  "custom": "",
                  "customPrivate": false,
                  "strictDateValidation": false,
                  "minLength": "",
                  "maxLength": "",
                  "pattern": ""
                },
                "key": "surname",
                "type": "textfield",
                "input": true,
                "hideOnChildrenHidden": false,
                "placeholder": "",
                "prefix": "",
                "customClass": "",
                "suffix": "",
                "multiple": false,
                "defaultValue": null,
                "protected": false,
                "unique": false,
                "persistent": true,
                "hidden": false,
                "clearOnHide": true,
                "refreshOn": "",
                "redrawOn": "",
                "modalEdit": false,
                "labelPosition": "top",
                "description": "",
                "errorLabel": "",
                "tooltip": "",
                "hideLabel": false,
                "tabindex": "",
                "disabled": false,
                "autofocus": false,
                "dbIndex": false,
                "customDefaultValue": "",
                "calculateValue": "",
                "widget": {
                  "type": "input"
                },
                "attributes": {},
                "validateOn": "change",
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": ""
                },
                "overlay": {
                  "style": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "allowCalculateOverride": false,
                "encrypted": false,
                "showCharCount": false,
                "showWordCount": false,
                "properties": {},
                "allowMultipleMasks": false,
                "mask": false,
                "inputType": "text",
                "inputFormat": "plain",
                "inputMask": "",
                "id": "elqd7hs"
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Other Names",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "other_name",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "hideOnChildrenHidden": false,
                "refreshOn": "",
                "inputType": "text",
                "id": "e76lbsg",
                "defaultValue": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "path": "columns",
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "eqsqnq"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Gender",
                "labelPosition": "top",
                "widget": null,
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "gender",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "ewwm17g",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Age",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "age",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "ensju8i",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Age Unit",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": true,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "year",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "epxyoxn",
                "defaultValue": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns1",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "eu24t5s",
        "path": "columns1"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Address",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "address",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "e45v1rm",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Phone Number",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "(999) 999-999-99",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "minLength": "",
                  "maxLength": "",
                  "pattern": "",
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "phone_number",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "phoneNumber",
                "input": true,
                "refreshOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "inputType": "tel",
                "id": "eqydxhq",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Type of Relationship",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "type_relationship",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "evh91y",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns2",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "ewkidhp",
        "path": "columns2"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Mode of Notification",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "mode_notification",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "eex41qj",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Duration of Partnership(Months)",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "duration_partnership",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "exklx0hi",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "History of GBV?",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "gbv",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "epflgq",
                "defaultValue": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns3",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "ey0t0d2e",
        "path": "columns3"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Phone Tracking",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "phone_tracking",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "e8nnpcc",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Home Visit?",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "home_tracking",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "e80k4vr",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Tracking Outcome",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "outcome",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "ej58x2",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns4",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "ew2h15",
        "path": "columns4"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Date Contact accepts HIV test",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "new Date()",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "date_test",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "prefix": "",
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "refreshOn": "",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "etrcq1a6",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "HIV Status",
                "labelPosition": "top",
                "widget": null,
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "hiv_status",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "ef9su0e",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Linked to HIV Care?",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "link_care",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "ea4zs6u",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns5",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "e01k2n8",
        "path": "columns5"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Agree to partner notification?",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "partner_notification",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "epv9ywn",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Service Provided?",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "service_provided",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "eq28nu9",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns6",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "eaauy14",
        "path": "columns6"
      },
      {
        "type": "button",
        "label": "Submit",
        "key": "submit",
        "size": "md",
        "block": false,
        "action": "submit",
        "disableOnInvalid": true,
        "theme": "primary",
        "input": true,
        "placeholder": "",
        "prefix": "",
        "customClass": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "hidden": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "tableView": false,
        "modalEdit": false,
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": {
          "type": "input"
        },
        "attributes": {},
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "conditional": {
          "show": null,
          "when": null,
          "eq": ""
        },
        "overlay": {
          "style": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "properties": {},
        "allowMultipleMasks": false,
        "leftIcon": "",
        "rightIcon": "",
        "dataGridLabel": true,
        "id": "eybgdf"
      }
    ]
  }