export const data = {
    "display": "",
    "components": [
      {
        "label": "HTML",
        "tag": "p",
        "className": "",
        "attrs": [
          {
            "attr": "",
            "value": ""
          }
        ],
        "content": "<span style=\"color:#B87108\">HIV RECENCY TESTING</span>\n<hr>",
        "refreshOnChange": false,
        "customClass": "",
        "hidden": false,
        "tableView": false,
        "modalEdit": false,
        "key": "html1",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "htmlelement",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "id": "eqlu7mp"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Participant Name",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "participantName",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "e3nsxlc",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Participant Number",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": true,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "participantNumber",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "hideOnChildrenHidden": false,
                "refreshOn": "",
                "inputType": "text",
                "id": "eqhfda",
                "defaultValue": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Confirm Participant Number",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "confirmParticipantNumber",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "e7kfybv",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "e7htb7o",
        "path": "columns"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Tester Name",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "testerName",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "e36riu",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Test Date ",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "new Date()",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": true,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "testDate",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "prefix": "",
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "refreshOn": "",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "esyhn98",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns1",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "emaabdp",
        "path": "columns1"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Control Line",
                "description": "",
                "tooltip": "",
                "shortcut": "",
                "inputType": "checkbox",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "errorLabel": "",
                "key": "controlLine",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "checkbox",
                "input": true,
                "placeholder": "",
                "prefix": "",
                "suffix": "",
                "multiple": false,
                "unique": false,
                "refreshOn": "",
                "labelPosition": "right",
                "widget": null,
                "validateOn": "change",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "dataGridLabel": true,
                "value": "",
                "name": "",
                "id": "e6o1zxn",
                "defaultValue": false,
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Verification Line",
                "description": "",
                "tooltip": "",
                "shortcut": "",
                "inputType": "checkbox",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "errorLabel": "",
                "key": "verificationLine",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "checkbox",
                "input": true,
                "placeholder": "",
                "prefix": "",
                "suffix": "",
                "multiple": false,
                "unique": false,
                "refreshOn": "",
                "labelPosition": "right",
                "widget": null,
                "validateOn": "change",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "dataGridLabel": true,
                "value": "",
                "name": "",
                "id": "ejwksg6",
                "defaultValue": false,
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Long Time Line",
                "description": "",
                "tooltip": "",
                "shortcut": "",
                "inputType": "checkbox",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "errorLabel": "",
                "key": "longTimeLine",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "checkbox",
                "input": true,
                "placeholder": "",
                "prefix": "",
                "suffix": "",
                "multiple": false,
                "unique": false,
                "refreshOn": "",
                "labelPosition": "right",
                "widget": null,
                "validateOn": "change",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "dataGridLabel": true,
                "value": "",
                "name": "",
                "id": "eivtddh",
                "defaultValue": false,
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns2",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "e8diliq",
        "path": "columns2"
      },
      {
        "label": "Enter Recency Interpretation",
        "labelPosition": "top",
        "placeholder": "",
        "description": "",
        "tooltip": "",
        "prefix": "",
        "suffix": "",
        "widget": {
          "type": "input"
        },
        "editor": "",
        "autoExpand": false,
        "customClass": "",
        "tabindex": "",
        "hidden": false,
        "hideLabel": false,
        "showWordCount": false,
        "showCharCount": false,
        "autofocus": false,
        "spellcheck": true,
        "disabled": false,
        "tableView": true,
        "modalEdit": false,
        "multiple": false,
        "persistent": true,
        "inputFormat": "html",
        "protected": false,
        "dbIndex": false,
        "case": "",
        "encrypted": false,
        "redrawOn": "",
        "clearOnHide": true,
        "customDefaultValue": "",
        "calculateValue": "",
        "allowCalculateOverride": false,
        "validateOn": "change",
        "validate": {
          "required": false,
          "pattern": "",
          "customMessage": "",
          "custom": "",
          "customPrivate": false,
          "json": "",
          "minLength": "",
          "maxLength": "",
          "minWords": "",
          "maxWords": "",
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "unique": false,
        "errorLabel": "",
        "key": "enterRecencyInterpretation",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "textarea",
        "wysiwyg": false,
        "input": true,
        "refreshOn": "",
        "allowMultipleMasks": false,
        "mask": false,
        "inputType": "text",
        "inputMask": "",
        "id": "ee5t76o",
        "defaultValue": "",
        "rows": 2
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Type of Sample",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "typeOfSample",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "esaxp2p",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Date sample collected",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": false,
                "allowInput": false,
                "format": "yyyy-MM-dd",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "new Date()",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": true,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "dateSampleCollected",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "prefix": "",
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "refreshOn": "",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": false,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "eba7gh9",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Date  sample Test",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd ",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "new Date()",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "dateSampleTest",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd ",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "hideOnChildrenHidden": false,
                "prefix": "",
                "refreshOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "e5063te"
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns3",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "e0fcqhn",
        "path": "columns3"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Date test done",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "new Date()",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "dateTestDone",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "prefix": "",
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "refreshOn": "",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "ehm4tro",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Viral Load Result Clasification",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "",
                      "value": ""
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "viralLoadResultClasification",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "e69nbp8",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Viral Load Result",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "viralLoadResult",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "eqsrue",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns4",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "eqkryd8",
        "path": "columns4"
      },
      {
        "label": "Final Recency Test Result",
        "labelPosition": "top",
        "placeholder": "",
        "description": "",
        "tooltip": "",
        "prefix": "",
        "suffix": "",
        "widget": {
          "type": "input"
        },
        "editor": "",
        "autoExpand": false,
        "customClass": "",
        "tabindex": "",
        "hidden": false,
        "hideLabel": false,
        "showWordCount": false,
        "showCharCount": false,
        "autofocus": false,
        "spellcheck": true,
        "disabled": false,
        "tableView": true,
        "modalEdit": false,
        "multiple": false,
        "persistent": true,
        "inputFormat": "html",
        "protected": false,
        "dbIndex": false,
        "case": "",
        "encrypted": false,
        "redrawOn": "",
        "clearOnHide": true,
        "customDefaultValue": "",
        "calculateValue": "",
        "allowCalculateOverride": false,
        "validateOn": "change",
        "validate": {
          "required": false,
          "pattern": "",
          "customMessage": "",
          "custom": "",
          "customPrivate": false,
          "json": "",
          "minLength": "",
          "maxLength": "",
          "minWords": "",
          "maxWords": "",
          "unique": false,
          "multiple": false,
          "strictDateValidation": false
        },
        "unique": false,
        "errorLabel": "",
        "key": "textArea",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "textarea",
        "wysiwyg": false,
        "input": true,
        "hideOnChildrenHidden": false,
        "refreshOn": "",
        "allowMultipleMasks": false,
        "mask": false,
        "inputType": "text",
        "inputMask": "",
        "id": "eyrjrly",
        "defaultValue": "",
        "rows": 1
      },
      {
        "type": "button",
        "label": "Submit",
        "key": "submit",
        "size": "md",
        "block": false,
        "action": "submit",
        "disableOnInvalid": true,
        "theme": "primary",
        "input": true,
        "placeholder": "",
        "prefix": "",
        "customClass": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "hidden": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "tableView": false,
        "modalEdit": false,
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": {
          "type": "input"
        },
        "attributes": {},
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "conditional": {
          "show": null,
          "when": null,
          "eq": ""
        },
        "overlay": {
          "style": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "properties": {},
        "allowMultipleMasks": false,
        "leftIcon": "",
        "rightIcon": "",
        "dataGridLabel": true,
        "id": "eite9s"
      }
    ]
  }