/**
 * @TYPES
 * ==============================================
 * PATIENTS
 */
export const PATIENTS_FETCH_ALL = 'PATIENTS_FETCH_ALL'
export const PATIENTS_FETCH_BY_ID = 'PATIENTS_FETCH_BY_ID'
export const PATIENTS_CREATE = 'PATIENTS_CREATE'
export const PATIENTS_UPDATE = 'PATIENTS_UPDATE'
export const PATIENTS_DELETE = 'PATIENTS_DELETE'
export const PATIENTS_ERROR = 'PATIENTS_ERROR'

/**
 * @TYPES
 * ===============================================
 * CHECKIN
 */
export const CHECKIN_FETCH_ALL = 'CHECKIN_FETCH_ALL'
export const CHECKIN_FETCH_BY_ID = 'CHECKIN_FETCH_BY_ID'
export const CHECKIN_CREATE = 'CHECKIN_CREATE'
export const CHECKIN_UPDATE = 'CHECKIN_UPDATE'
export const CHECKIN_DELETE = 'CHECKIN_DELETE'
export const CHECKIN_ERROR = 'CHECKIN_ERROR'

/**
 * @TYPES
 * ===============================================
 * ENCOUNTER
 */
export const ENCOUNTER_FETCH_ALL = 'ENCOUNTER_FETCH_ALL'
export const ENCOUNTER_FETCH_BY_ID = 'ENCOUNTER_FETCH_BY_ID'
export const ENCOUNTER_CREATE = 'ENCOUNTER_CREATE'
export const ENCOUNTER_UPDATE = 'ENCOUNTER_UPDATE'
export const ENCOUNTER_DELETE = 'ENCOUNTER_DELETE'
export const ENCOUNTER_ERROR = 'ENCOUNTER_ERROR'


/**
 * @TYPES
 * ===============================================
 * LABORATORY
 */
export const LABORATORY_FETCH_ALL = 'LABORATORY_FETCH_ALL'
export const LABORATORY_TESTORDER = 'LABORATORY_TESTORDER'
export const LABORATORY_TESTRESULT = 'LABORATORY_TESTRESULT'
export const LABORATORY_CREATE = 'LABORATORY_CREATE'
export const LABORATORY_UPDATE = 'LABORATORY_UPDATE'
export const LABORATORY_DELETE = 'LABORATORY_DELETE'
export const LABORATORY_ERROR = 'LABORATORY_ERROR'
export const CREATE_COLLECT_SAMPLE = 'CREATE_COLLECT_SAMPLE'
export const ERROR_CREATE_COLLECT_SAMPLE = 'ERROR_CREATE_COLLECT_SAMPLE'
export const ERROR_LABORATORY_TESTORDER = 'ERROR_LABORATORY_TESTORDER'



