export const initialfieldState_patientRegsitration = {
        hospitalNumber:'',
        firstName: '',
        lastName: '', 
        email:'',
        facilityId: '1',
        dobEstimated:'',
        educationId:'',
        genderId:'',
        maritalStatusId:'',
        occupationId:'',
        alternatePhoneNumber:'',
        personRelativeDTOList:[],
        address1:'',
        city:'',
        countryId:'',
        landmark:'',
        provinceId:'',
        zipCode:'',
        stateId:'',
        street:'',
        dob:'',
        dateRegistration: new Date(),
        age:''

}
