export const initialfieldState_patientRegistration = {
  hospitalNumber: '',
  firstName: '',
  lastName: '',
  email: '',
  facilityId: '1',
  dobEstimated: '',
  educationId: '',
  genderId: '',
  maritalStatusId: '',
  occupationId: '',
  alternatePhoneNumber: '',
  personRelativeDTOs: [],
  address: '',
  city: '',
  countryId: '',
  landmark: '',
  provinceId: '',
  zipCode: '',
  stateId: '',
  street: '',
  dob: '',
  dateRegistration: new Date()
}
